spring.application.name=minlog

# DB 접속 정보 (.env 파일에서 로드)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# JWT 시크릿 키 (.env 파일에서 로드)
jwt.secret=${JWT_SECRET}
